api:
  build: ./
  working_dir: /go/src/github.com/charlires/goapp1
  volumes:
    - .:/go/src/github.com/charlires/goapp1
  links:
    - database
  environment:
    - DB_NAME=advanced-golang-db
  command: go run main.go

database:
  image: mongo:3.0
  command: mongod --smallfiles --quiet --logpath=/dev/null
